version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      DATABASE_URL: postgresql://root:abc@db:5432/classroom?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: classroom
    ports:
      - "9999:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
